title: "C"
description: "Repositori Kuliah Bahasa Pemrograman C"
theme: jekyll-theme-midnight
markdown: kramdown
lang: "id"  
timezone: Asia/Jakarta

author:
  name: "Budi Imam Prasetyo"
  email: "budiimamprsty@gmail.com"
  github: "budi-imam-prasetyo"

show_downloads: true
